### ISSUE TITLE
Issue with `make run`

### ISSUE THREAD

**Issue by geonnave** [AnimaGUS-minerva/studio#1]
Steps:
1. clone project and `make init`
2. `cd examples/esp32-no_std` and `make run`
3. had an error which required me to `cargo install cargo-xbuild`
4. next, `make run` resulted in the following:

```
make esp32-build-module
make[1]: Entering directory '/home/geovane/dev/swarm/dev/tmp/explore-riot/iot-rust-module-studio/examples/esp32-no_std'
RUST_MODULE_STUDIO=/home/geovane/dev/swarm/dev/tmp/explore-riot/iot-rust-module-studio source ../esp32.setup && \
        XTENSA_GCC=/home/geovane/dev/swarm/dev/tmp/explore-riot/iot-rust-module-studio/toolchain/xtensa/riot/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc \
        cargo +xtensa xbuild --lib --release --target xtensa-esp32-none-elf 
error: failed to copy Cargo.lock from `/home/geovane/dev/swarm/dev/tmp/explore-riot/iot-rust-module-studio/toolchain/xtensa/rustc/rust_xtensa/src/../Cargo.lock` to `/tmp/cargo-xbuildU6rXO1/Cargo.lock`
caused by: No such file or directory (os error 2)
make[1]: *** [../esp32.mk:11: esp32-build-module] Error 1
make[1]: Leaving directory '/home/geovane/dev/swarm/dev/tmp/explore-riot/iot-rust-module-studio/examples/esp32-no_std'
```

Tested on rust both stable & nightly, same result.

**Comment by j-devel** [comment]
Thanks for reporting this!

Currently, the ESP32 Rust compiler used in this repository requires [this compiler_builtins crate workaround](https://github.com/AnimaGUS-minerva/iot-rust-module-studio/blob/7f76a30f9ac38e8659c93831703056e76396b44f/examples/esp32.mk#L7-L15), and once this configuration is broken for whatever reasons, the issue you reported could happen.

Here's how to fix it as far as I investigated the situation --

1) First, make sure you preserve these lines:

https://github.com/AnimaGUS-minerva/iot-rust-module-studio/blob/7f76a30f9ac38e8659c93831703056e76396b44f/examples/esp32-no_std/.cargo/config#L3-L6

In case you did invoke `make run` after modifying this part previously, the 'Cargo.lock' error could arise and stick.

2) You can resolve the 'Cargo.lock' error by removing the (presumably) broken local Rust lib by:

```
$ cd examples/esp32-no_std
$ rm -rf ../../toolchain/xtensa/xtensa-esp32-none-elf
```

3) Finally, `make run` should restore the lib, and build will start working again.

```
$ make run
make esp32-build-module
make[1]: Entering directory '/media/iot-rust-module-studio--issue-1/examples/esp32-no_std'
Setting up pre-built xtensa-esp32-none-elf to workaround build errors of the compiler_builtins crate
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   211  100   211    0     0    383      0 --:--:-- --:--:-- --:--:--   382
100   696  100   696    0     0    733      0 --:--:-- --:--:-- --:--:--   733
100 16.8M  100 16.8M    0     0   331k      0  0:00:52  0:00:52 --:--:-- 3056k
RUST_MODULE_STUDIO=/media/iot-rust-module-studio--issue-1 source ../esp32.setup && \
        XTENSA_GCC=/media/iot-rust-module-studio--issue-1/toolchain/xtensa/riot/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc \
	cargo +xtensa xbuild --lib --release --target xtensa-esp32-none-elf
   Compiling esp32-no_std v0.1.0 (/media/iot-rust-module-studio--issue-1/examples/esp32-no_std)
    Finished release [optimized] target(s) in 0.09s
ls -lrt target/xtensa-esp32-none-elf/release/*.a
-rw-rw-r-- 2 a a 2265424 Dec 25 12:01 target/xtensa-esp32-none-elf/release/librustmod.a
make[1]: Leaving directory '/media/iot-rust-module-studio--issue-1/examples/esp32-no_std'
make esp32-build-riot

....
```

**Comment by j-devel** [comment]
Okay, [the latest CI just detected the exact error](https://github.com/AnimaGUS-minerva/iot-rust-module-studio/runs/4976242678?check_suite_focus=true#step:10:175).

`cargo-xbuild` built by the recent x86_64 rustc (used by the Linux host) is no longer compatible with our (ancient) custom rustc xtensa.  So, we will be migrating to a latest one at (https://github.com/esp-rs/rust-build).

Please ignore my previous comment.  I would like to update this thread again after the migration is done.

**Comment by j-devel** [comment]
We have replaced the broken Rust ESP toolchain; as of c32918e the following steps should just work

> Steps:
> 
> 1. clone project and `make init`
> 2. `cd examples/esp32-no_std` and `make run`
